VERSION_YEAR = 2023
VERSION_MONTH = int('05')
VERSION_DAY = int('23')
VERSION_HOUR = int('14')
VERSION_MINUTE = int('57')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202305231457
version_date = '2023/05/23 14:57'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
