VERSION_YEAR = 2025
VERSION_MONTH = int('02')
VERSION_DAY = int('08')
VERSION_HOUR = int('20')
VERSION_MINUTE = int('30')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202502082030
version_date = '2025/02/08 20:30'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
